package com.xujun.charting.interfaces;

import com.xujun.charting.data.DataSet;
import com.xujun.charting.data.Entry;

/**
 * Created by xujunwu on 14/12/31.
 */
public interface OnDrawListener {
    /**
     * Called whenever an entry is added with the finger. Note this is also called for entries that are generated by the
     * library, when the touch gesture is too fast and skips points.
     *
     * @param entry
     *            the last drawn entry
     */
    public void onEntryAdded(Entry entry);

    /**
     * Called whenever an entry is moved by the user after beeing highlighted
     *
     * @param entry
     */
    public void onEntryMoved(Entry entry);

    /**
     * Called when drawing finger is lifted and the draw is finished.
     *
     * @param dataSet
     *            the last drawn DataSet
     */
    public void onDrawFinished(DataSet dataSet);
}
